### ISSUE TITLE
Release is failing to compile due to the tar changes in the latest Windows patches

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/windows2019fs-release#3]
During compilation this release is failing on the latest stemcells due to the changes in the latest Windows patches (see https://github.com/cloudfoundry/bosh-agent/commit/ff3a67033e7b7d55fd12d26d79b3aacce1dca1e1 for reference).  The packaging script at https://github.com/cloudfoundry/windows2019fs-release/blob/master/packages/windows2019fs/packaging#L4 will need to be modified to dereference the symlink for BOSH_INSTALL_TARGET to a real path.

For example, changing this:

$BOSH_INSTALL_TARGET = Resolve-Path "${env:BOSH_INSTALL_TARGET}"

to this:

$BOSH_INSTALL_TARGET = (Get-Item(Resolve-Path "${env:BOSH_INSTALL_TARGET}")).Target

Should work.

**Comment by amhuber** [comment]
Well, that should have worked except C:\var\vcap\data is also a symlink to E:\ and I can't find any equivalent to the golang EvalSymlinks in either PowerShell or a .NET class that just figures out what the real path is in one step.  This feels a little inelegant but it works (I was able to successfully compile with this code):

    $BOSH_INSTALL_TARGET = (Get-Item(Resolve-Path "${env:BOSH_INSTALL_TARGET}")).Target
    $DATA_PATH = (Get-Item("C:\var\vcap\data")).Target
    $BOSH_INSTALL_TARGET = $BOSH_INSTALL_TARGET.Replace("C:\var\vcap\data\", $DATA_PATH)

**Comment by MarcPaquette** [comment]
Hi @amhuber 

[We committed a fix](https://github.com/cloudfoundry/windows2019fs-release/commit/9d9a400a01ede5fca5272b02b1256eff9a8208c3) that's available in [v2.33.2](https://github.com/cloudfoundry/windows2019fs-release/releases/tag/v2.33.2)

Does this solve your issue?

**Comment by amhuber** [comment]
That looks like it should do it, I'll test it out as soon as possible and close the issue when it's confirmed.  Thanks!

**Comment by amhuber** [comment]
Looks good, the new version did compile and deploy successfully.  Thanks again for the quick fix.
